// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.24.2
// source: analytics.proto

package analytics

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	AnalyticsService_GetTotalSales_FullMethodName       = "/AnalyticsService/GetTotalSales"
	AnalyticsService_GetSalesByProductId_FullMethodName = "/AnalyticsService/GetSalesByProductId"
	AnalyticsService_GetTopFiveCustomers_FullMethodName = "/AnalyticsService/GetTopFiveCustomers"
)

// AnalyticsServiceClient is the client API for AnalyticsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AnalyticsServiceClient interface {
	GetTotalSales(ctx context.Context, in *GetTotalSalesRequest, opts ...grpc.CallOption) (*GetTotalSalesResponse, error)
	GetSalesByProductId(ctx context.Context, in *GetSalesByProductIdRequest, opts ...grpc.CallOption) (*GetSalesByProductIdResponse, error)
	GetTopFiveCustomers(ctx context.Context, in *GetTopFiveCustomersRequest, opts ...grpc.CallOption) (*GetTopFiveCustomersResponse, error)
}

type analyticsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAnalyticsServiceClient(cc grpc.ClientConnInterface) AnalyticsServiceClient {
	return &analyticsServiceClient{cc}
}

func (c *analyticsServiceClient) GetTotalSales(ctx context.Context, in *GetTotalSalesRequest, opts ...grpc.CallOption) (*GetTotalSalesResponse, error) {
	out := new(GetTotalSalesResponse)
	err := c.cc.Invoke(ctx, AnalyticsService_GetTotalSales_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analyticsServiceClient) GetSalesByProductId(ctx context.Context, in *GetSalesByProductIdRequest, opts ...grpc.CallOption) (*GetSalesByProductIdResponse, error) {
	out := new(GetSalesByProductIdResponse)
	err := c.cc.Invoke(ctx, AnalyticsService_GetSalesByProductId_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analyticsServiceClient) GetTopFiveCustomers(ctx context.Context, in *GetTopFiveCustomersRequest, opts ...grpc.CallOption) (*GetTopFiveCustomersResponse, error) {
	out := new(GetTopFiveCustomersResponse)
	err := c.cc.Invoke(ctx, AnalyticsService_GetTopFiveCustomers_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AnalyticsServiceServer is the server API for AnalyticsService service.
// All implementations must embed UnimplementedAnalyticsServiceServer
// for forward compatibility
type AnalyticsServiceServer interface {
	GetTotalSales(context.Context, *GetTotalSalesRequest) (*GetTotalSalesResponse, error)
	GetSalesByProductId(context.Context, *GetSalesByProductIdRequest) (*GetSalesByProductIdResponse, error)
	GetTopFiveCustomers(context.Context, *GetTopFiveCustomersRequest) (*GetTopFiveCustomersResponse, error)
	mustEmbedUnimplementedAnalyticsServiceServer()
}

// UnimplementedAnalyticsServiceServer must be embedded to have forward compatible implementations.
type UnimplementedAnalyticsServiceServer struct {
}

func (UnimplementedAnalyticsServiceServer) GetTotalSales(context.Context, *GetTotalSalesRequest) (*GetTotalSalesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTotalSales not implemented")
}
func (UnimplementedAnalyticsServiceServer) GetSalesByProductId(context.Context, *GetSalesByProductIdRequest) (*GetSalesByProductIdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSalesByProductId not implemented")
}
func (UnimplementedAnalyticsServiceServer) GetTopFiveCustomers(context.Context, *GetTopFiveCustomersRequest) (*GetTopFiveCustomersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTopFiveCustomers not implemented")
}
func (UnimplementedAnalyticsServiceServer) mustEmbedUnimplementedAnalyticsServiceServer() {}

// UnsafeAnalyticsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AnalyticsServiceServer will
// result in compilation errors.
type UnsafeAnalyticsServiceServer interface {
	mustEmbedUnimplementedAnalyticsServiceServer()
}

func RegisterAnalyticsServiceServer(s grpc.ServiceRegistrar, srv AnalyticsServiceServer) {
	s.RegisterService(&AnalyticsService_ServiceDesc, srv)
}

func _AnalyticsService_GetTotalSales_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTotalSalesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticsServiceServer).GetTotalSales(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalyticsService_GetTotalSales_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyticsServiceServer).GetTotalSales(ctx, req.(*GetTotalSalesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnalyticsService_GetSalesByProductId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSalesByProductIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticsServiceServer).GetSalesByProductId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalyticsService_GetSalesByProductId_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyticsServiceServer).GetSalesByProductId(ctx, req.(*GetSalesByProductIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnalyticsService_GetTopFiveCustomers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTopFiveCustomersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticsServiceServer).GetTopFiveCustomers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalyticsService_GetTopFiveCustomers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyticsServiceServer).GetTopFiveCustomers(ctx, req.(*GetTopFiveCustomersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AnalyticsService_ServiceDesc is the grpc.ServiceDesc for AnalyticsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AnalyticsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "AnalyticsService",
	HandlerType: (*AnalyticsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetTotalSales",
			Handler:    _AnalyticsService_GetTotalSales_Handler,
		},
		{
			MethodName: "GetSalesByProductId",
			Handler:    _AnalyticsService_GetSalesByProductId_Handler,
		},
		{
			MethodName: "GetTopFiveCustomers",
			Handler:    _AnalyticsService_GetTopFiveCustomers_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "analytics.proto",
}
